# Generated by Django 2.1.3 on 2018-11-26 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('H', 'Thursday'), ('F', 'Friday'), ('MW', 'Monday Wednesday'), ('TH', 'Tuesday Thursday'), ('MWF', 'Monday Wednesday Friday'), ('None', 'Unassigned')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='section',
            name='endTime',
            field=models.CharField(default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='section',
            name='startTime',
            field=models.CharField(default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='section',
            name='stype',
            field=models.CharField(choices=[('lab', 'Lab'), ('lecture', 'Lecture'), ('None', 'Unassigned')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('T', 'TA'), ('I', 'Instructor'), ('A', 'Administrator'), ('S', 'Supervisor'), ('None', 'Unassigned')], max_length=13),
        ),
    ]
