# Generated by Django 2.1.3 on 2018-12-02 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_view_course', 'Can view course data'), ('can_edit_course', 'Can edit course data'), ('can_delete_course', 'Can delete a course'), ('can_create_course', 'Can create courses'), ('can_add_course', 'Cam add a course'), ('can_assign_ins', 'Can assign instructors'))},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'permissions': (('can_create_section', 'Can create sections'), ('can_edit_section', 'Can edit sections'), ('can_delete_section', 'Can delete sections'), ('can_view_section', 'Can view sections'), ('can_assign_ta', "Can assign TA's"))},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('can_create_user', 'Can create users'), ('can_edit_user', 'Can edit users'), ('can_edit_self', 'Can edit users'), ('can_delete_user', 'Can delete users'), ('can_view_user', 'Can view users'), ('can_view_private', 'Can view private user data'), ('can_email_all', 'Can send emails to all users'), ('can_email_tas', 'Can send emails'))},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('H', 'Thursday'), ('F', 'Friday'), ('MW', 'Monday Wednesday'), ('TH', 'Tuesday Thursday'), ('MWF', 'Monday Wednesday Friday'), (None, 'None')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='stype',
            field=models.CharField(blank=True, choices=[('lab', 'Lab'), ('lecture', 'Lecture'), (None, 'None')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]