# Generated by Django 2.1.3 on 2018-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='sec', to='TAServer.Section'),
        ),
    ]
