# Generated by Django 2.1.3 on 2018-11-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0002_auto_20181125_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='endTime',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='section',
            name='startTime',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
