# Generated by Django 2.1.3 on 2018-11-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0002_auto_20181129_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
