# Generated by Django 2.1.3 on 2018-11-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0004_auto_20181129_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('H', 'Thursday'), ('F', 'Friday'), ('MW', 'Monday Wednesday'), ('TH', 'Tuesday Thursday'), ('MWF', 'Monday Wednesday Friday'), (None, 'None')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='stype',
            field=models.CharField(blank=True, choices=[('lab', 'Lab'), ('lecture', 'Lecture'), (None, 'None')], default=None, max_length=10, null=True),
        ),
    ]
