# Generated by Django 2.1.3 on 2018-11-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0004_auto_20181125_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='snum',
            field=models.CharField(max_length=4),
        ),
    ]
