# Generated by Django 2.1.3 on 2018-11-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0005_auto_20181125_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='stype',
            field=models.CharField(blank=True, choices=[('lab', 'Lab'), ('lecture', 'Lecture'), ('None', 'Unassigned')], max_length=10, null=True),
        ),
    ]
