# Generated by Django 2.1.3 on 2018-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAServer', '0006_auto_20181125_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='section',
            name='startTime',
        ),
        migrations.AddField(
            model_name='section',
            name='time',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
